// packages/client/src/components/table/WarrantyItem.vue
<script setup lang="ts">
import { Warranty } from "../../models/model.warranty";
import { getFormattedDate } from "../../utils/util.date";
import ColorDate from "../ColorDate.vue";

const { warranty } = defineProps<{
  warranty: Warranty;
}>();
</script>

<template>
  <tr class="hover:bg-gray-200 border-b border-t border-gray-300">
    <td class="align-top w-1/4 py-2">{{ warranty.productName }}</td>
    <td class="align-top py-2">
      {{ getFormattedDate(warranty.effectiveDate) }}
    </td>
    <td class="align-top py-2">
      <ColorDate :date="warranty.expireDate" />
    </td>
    <td class="align-top break-words min-w-min w-1/2 py-2">
      {{ warranty.note }}
    </td>
    <td>
      <button>
        <div
          class="material-symbols-outlined text-xl text-gray-700 cursor-pointer select-none rounded-full w-7 h-7 flex items-center justify-center hover:bg-gray-400"
        >
          edit
        </div>
      </button>
    </td>
  </tr>
</template>

// packages/client/app/(components)/WarrantyItem.tsx
import { getFormattedDate } from "@/utils/util.date";
import { Warranty } from "../../../shared/models/model.warranty";

const CustomTd = ({
  children,
  className,
}: {
  children: React.ReactNode;
  className?: string;
}) => {
  return <td className={`${className} py-4`}>{children}</td>;
};

type WarrantyItemProps = {
  warranty: Warranty;
};

export const WarrantyItem = ({ warranty }: WarrantyItemProps) => {
  return (
    <tr className="border-t border-b border-n-gray odd:bg-white odd:bg-opacity-50 even:bg-n-white cursor-pointer select-none">
      <CustomTd>{warranty.productName}</CustomTd>
      <CustomTd>{getFormattedDate(new Date(warranty.effectiveDate))}</CustomTd>
      <CustomTd
        className={
          new Date(warranty.expireDate) < new Date(Date.now())
            ? "text-red-600"
            : "text-green-600"
        }
      >
        {getFormattedDate(new Date(warranty.expireDate))}
      </CustomTd>
      <CustomTd>
        <span className="material-symbols-outlined flex items-center">
          chevron_right
        </span>
      </CustomTd>
    </tr>
  );
};
