// packages/client/app/(components)/WarrantyItem.tsx
import { getFormattedDate } from "@/utils/util.date";
import { Warranty } from "../../../shared/models/model.warranty";

const CustomTd = ({
  children,
  className,
}: {
  children: React.ReactNode;
  className?: string;
}) => {
  return <td className={`${className} py-4`}>{children}</td>;
};

type WarrantyItemProps = {
  warranty: Warranty;
};

export const WarrantyItem = ({ warranty }: WarrantyItemProps) => {
  return (
    <tr className="border-t border-b border-n-gray odd:bg-white odd:bg-opacity-50 even:bg-n-white cursor-pointer select-none">
      <CustomTd>{warranty.productName}</CustomTd>
      <CustomTd>{getFormattedDate(new Date(warranty.effectiveDate))}</CustomTd>
      <CustomTd
        className={
          new Date(warranty.expireDate) < new Date(Date.now())
            ? "text-red-600"
            : "text-green-600"
        }
      >
        {getFormattedDate(new Date(warranty.expireDate))}
      </CustomTd>
      <CustomTd>
        <span className="material-symbols-outlined flex items-center">
          chevron_right
        </span>
      </CustomTd>
    </tr>
  );
};

// packages/client/src/components/WarrantyItem.vue
<script setup lang="ts">
import { Warranty } from "../models/model.warranty";
import { getFormattedDate } from "../utils/util.date";
import { ref } from "vue";

const { warranty } = defineProps<{
  warranty: Warranty;
}>();

let detail = ref(false);

const toggleDetail = () => {
  detail.value = !detail.value;
};
</script>

<template>
  <tr
    v-on:click="toggleDetail()"
    class="hover:bg-gray-300 cursor-pointer select-none"
  >
    <td>{{ warranty.productName }}</td>
    <td>{{ getFormattedDate(warranty.effectiveDate) }}</td>
    <td>{{ getFormattedDate(warranty.expireDate) }}</td>
    <td class="flex justify-center items-end py-2">
      <span class="material-symbols-outlined">chevron_right</span>
    </td>
  </tr>
  <div v-if="detail">detail</div>
</template>
